import * as React from 'react';
import { IFileTreeXHandle, IFileTreeXProps } from '../types';
export declare class FileTreeX extends React.Component<IFileTreeXProps> {
    private fileTreeHandle;
    private readonly activeFileDec;
    private readonly pseudoActiveFileDec;
    private activeFile;
    private pseudoActiveFile;
    private readonly wrapperRef;
    private readonly events;
    private readonly disposables;
    private keyboardHotkeys;
    private fileTreeEvent;
    private readonly hoverTimeoutId;
    private readonly hoverDispatchId;
    constructor(props: IFileTreeXProps);
    render(): React.JSX.Element;
    componentDidMount(): void;
    componentWillUnmount(): void;
    private readonly handleTreeEvent;
    private readonly handleTreeReady;
    private readonly onItemMouseEnter;
    private readonly onItemMouseLeave;
    private readonly setActiveFile;
    private readonly ensureVisible;
    private readonly deSelectActiveFile;
    private readonly setPseudoActiveFile;
    private readonly create;
    private readonly update;
    private readonly refresh;
    private readonly unload;
    private readonly remove;
    private readonly first;
    private readonly parent;
    private readonly hasParent;
    private readonly children;
    private readonly isOpen;
    private readonly isClosed;
    private readonly itemData;
    private readonly setLabel;
    private readonly changeDirectoryCount;
    private readonly closeDir;
    private readonly toggleDirectory;
    private readonly addIcon;
    private readonly addCssClass;
    private readonly toggleItemLoader;
    private readonly showLoader;
    private readonly hideLoader;
    private readonly handleBlur;
    private readonly handleItemClicked;
    private readonly handleItemDoubleClicked;
    private readonly getItemFromDOM;
    private readonly getDOMFromItem;
    private readonly handleClick;
    private readonly handleItemCtxMenu;
    private readonly handleKeyDown;
    private readonly onResize;
    private readonly resize;
    private readonly changeResolvePath;
}
export { IFileTreeXHandle, IFileTreeXProps };
//# sourceMappingURL=index.d.ts.map